---
version: 2.1

executors:
  linux-x86_64:
    docker:
      - image: cimg/rust:1.91.1
  base:
    docker:
      - image: cimg/base:current

jobs:
  test:
    executor: linux-x86_64
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: |
            cargo install cargo2junit
            mkdir -p test-results
      - run:
          name: Executing tests
          command: RUSTC_BOOTSTRAP="1" cargo test --no-fail-fast -- -Z unstable-options --format json --report-time | cargo2junit > test-results/test-results.xml
      - store_test_results:
          path: test-results
  build-linux-x86_64:
    executor: base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
            docker image build --target=prod --tag=sardylan/olg-server:${CIRCLE_TAG} .
            docker image push sardylan/olg-server:${CIRCLE_TAG}

workflows:
  test_and_build:
    jobs:
      - test:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - build-linux-x86_64:
          context: "Docker Hub"
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
